export { default as Plus } from './Plus'
export { default as CaretRight } from './CaretRight'
export { default as Instagram } from './Instagram'
export { default as Twitter } from './Twitter'
export { default as Discord } from './Discord'
export { default as Github } from './Github'
export { default as Link } from './Link'
